export interface WeatherCodeInfo {
  code: number;
  label: string;
  description: string;
  iconName: 'sun' | 'cloud-sun' | 'cloud' | 'cloud-fog' | 'cloud-drizzle' | 'cloud-rain' | 'cloud-snow' | 'cloud-lightning' | 'snowflake';
  badgeColor: string; // Tailwind class
  isPrecipitation: boolean;
}

export const WMO_WEATHER_CODES: Record<number, WeatherCodeInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Completely clear skies with strong sunshine',
    iconName: 'sun',
    badgeColor: 'text-amber-600 bg-amber-50 border-amber-200',
    isPrecipitation: false,
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly sunny with minor scattered clouds',
    iconName: 'sun',
    badgeColor: 'text-amber-600 bg-amber-50 border-amber-200',
    isPrecipitation: false,
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Intermittent clouds and sunshine',
    iconName: 'cloud-sun',
    badgeColor: 'text-sky-700 bg-sky-50 border-sky-200',
    isPrecipitation: false,
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Dense unbroken cloud cover',
    iconName: 'cloud',
    badgeColor: 'text-slate-600 bg-slate-100 border-slate-200',
    isPrecipitation: false,
  },
  45: {
    code: 45,
    label: 'Fog',
    description: 'Dense fog reducing ground visibility',
    iconName: 'cloud-fog',
    badgeColor: 'text-slate-600 bg-slate-100 border-slate-200',
    isPrecipitation: false,
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Icy fog depositing freezing crystal rime',
    iconName: 'cloud-fog',
    badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200',
    isPrecipitation: false,
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Fine mist and light intermittent drizzle',
    iconName: 'cloud-drizzle',
    badgeColor: 'text-blue-700 bg-blue-50 border-blue-200',
    isPrecipitation: true,
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Consistent light drizzle',
    iconName: 'cloud-drizzle',
    badgeColor: 'text-blue-700 bg-blue-50 border-blue-200',
    isPrecipitation: true,
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy continuous drizzle with wet roads',
    iconName: 'cloud-drizzle',
    badgeColor: 'text-blue-700 bg-blue-50 border-blue-200',
    isPrecipitation: true,
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    description: 'Freezing drizzle causing slick surfaces',
    iconName: 'snowflake',
    badgeColor: 'text-cyan-700 bg-cyan-50 border-cyan-200',
    isPrecipitation: true,
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Dense freezing drizzle, risk of glaze ice',
    iconName: 'snowflake',
    badgeColor: 'text-cyan-700 bg-cyan-50 border-cyan-200',
    isPrecipitation: true,
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light steady rainfall',
    iconName: 'cloud-rain',
    badgeColor: 'text-blue-700 bg-blue-50 border-blue-200',
    isPrecipitation: true,
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Steady moderate rainfall',
    iconName: 'cloud-rain',
    badgeColor: 'text-blue-800 bg-blue-50 border-blue-200',
    isPrecipitation: true,
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Intense rain with significant surface runoff',
    iconName: 'cloud-rain',
    badgeColor: 'text-blue-900 bg-blue-100 border-blue-300',
    isPrecipitation: true,
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Freezing precipitation forming road ice',
    iconName: 'snowflake',
    badgeColor: 'text-cyan-800 bg-cyan-50 border-cyan-200',
    isPrecipitation: true,
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Severe freezing rain, hazardous travel',
    iconName: 'snowflake',
    badgeColor: 'text-cyan-900 bg-cyan-100 border-cyan-300',
    isPrecipitation: true,
  },
  71: {
    code: 71,
    label: 'Slight Snow',
    description: 'Light snowfall flakes with slight accumulation',
    iconName: 'cloud-snow',
    badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200',
    isPrecipitation: true,
  },
  73: {
    code: 73,
    label: 'Moderate Snow',
    description: 'Moderate steady snowfall',
    iconName: 'cloud-snow',
    badgeColor: 'text-indigo-800 bg-indigo-50 border-indigo-200',
    isPrecipitation: true,
  },
  75: {
    code: 75,
    label: 'Heavy Snow',
    description: 'Heavy snow storm with reduced visibility',
    iconName: 'snowflake',
    badgeColor: 'text-indigo-900 bg-indigo-100 border-indigo-300',
    isPrecipitation: true,
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Frozen tiny snow grain particles',
    iconName: 'snowflake',
    badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200',
    isPrecipitation: true,
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Brief intermittent rain showers',
    iconName: 'cloud-rain',
    badgeColor: 'text-blue-700 bg-blue-50 border-blue-200',
    isPrecipitation: true,
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Passing rain showers of moderate strength',
    iconName: 'cloud-rain',
    badgeColor: 'text-blue-800 bg-blue-50 border-blue-200',
    isPrecipitation: true,
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Heavy torrential downpours',
    iconName: 'cloud-rain',
    badgeColor: 'text-blue-900 bg-blue-100 border-blue-300',
    isPrecipitation: true,
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Scattered brief snow squalls',
    iconName: 'cloud-snow',
    badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200',
    isPrecipitation: true,
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense passing snow squalls',
    iconName: 'snowflake',
    badgeColor: 'text-indigo-900 bg-indigo-100 border-indigo-300',
    isPrecipitation: true,
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Active electrical lightning with rain',
    iconName: 'cloud-lightning',
    badgeColor: 'text-purple-800 bg-purple-50 border-purple-200',
    isPrecipitation: true,
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Slight Hail',
    description: 'Thunderstorm with small hailstones',
    iconName: 'cloud-lightning',
    badgeColor: 'text-purple-900 bg-purple-100 border-purple-300',
    isPrecipitation: true,
  },
  99: {
    code: 99,
    label: 'Thunderstorm with Heavy Hail',
    description: 'Severe storm with dangerous hailstones',
    iconName: 'cloud-lightning',
    badgeColor: 'text-purple-950 bg-purple-100 border-purple-400',
    isPrecipitation: true,
  },
};

export function getWeatherCodeInfo(code: number): WeatherCodeInfo {
  return (
    WMO_WEATHER_CODES[code] || {
      code,
      label: 'Partly Cloudy',
      description: 'Variable cloudiness',
      iconName: 'cloud-sun',
      badgeColor: 'text-slate-600 bg-slate-100 border-slate-200',
      isPrecipitation: false,
    }
  );
}
